from getTrDizinPublication import getTrDizinPublication

trDizinNumara = input("trdizin numarasını giriniz:")
tr = getTrDizinPublication ()
tr.trDizinPublication (trDizinNumara)

print ("", (tr.dikkat))
print ("Trdizin id: ", (tr.trdizinid))
print ("doi: ", (tr.doi))
print ("Başlık: ", (tr.ArticleTitle)) 
print ("Dergi ismi: ", (tr.dergi))
print ("ISSN: ", (tr.ISSN))
print ("eISSN: ", (tr.eISSN))
print ("Yıl: ", (tr.Year))
print ("Cilt: ", (tr.Volume))
print ("Sayı: ", (tr.Issue))
print (f"Sayfa/numara: {tr.StartPage} - {tr.EndPage}")
print ("Yazar sayısı: ", (tr.yazarS))
print ("Yazar(lar): ", (tr.yazarlar))
print ("Dergi numarası: ", (tr.dergiLinki))
print ("Yayın türü: ", (tr.PublicationType))
print ("Makale türü: ", (tr.ArticleType))
print ("Özet: ", (tr.AbstractText))
